// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYImF-uGW1-zc4gVQLMvOMqf3bkL3J7j0',
    appId: '1:81898159963:web:362a6d64279f7c7b75e47e',
    messagingSenderId: '81898159963',
    projectId: 'controlapp-7f8f5',
    authDomain: 'controlapp-7f8f5.firebaseapp.com',
    databaseURL: 'https://controlapp-7f8f5-default-rtdb.firebaseio.com',
    storageBucket: 'controlapp-7f8f5.appspot.com',
    measurementId: 'G-T6EQMPV61K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2pUd_78y-lB0JsaZvjmdncXZyYCSvfE',
    appId: '1:81898159963:android:7cf82ae6df13097275e47e',
    messagingSenderId: '81898159963',
    projectId: 'controlapp-7f8f5',
    databaseURL: 'https://controlapp-7f8f5-default-rtdb.firebaseio.com',
    storageBucket: 'controlapp-7f8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXwkrNNlRplzxdfaIcJoez4Nbh2ofTLU',
    appId: '1:81898159963:ios:6971aa6b3f63c3a775e47e',
    messagingSenderId: '81898159963',
    projectId: 'controlapp-7f8f5',
    databaseURL: 'https://controlapp-7f8f5-default-rtdb.firebaseio.com',
    storageBucket: 'controlapp-7f8f5.appspot.com',
    iosBundleId: 'com.example.controlapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRXwkrNNlRplzxdfaIcJoez4Nbh2ofTLU',
    appId: '1:81898159963:ios:6971aa6b3f63c3a775e47e',
    messagingSenderId: '81898159963',
    projectId: 'controlapp-7f8f5',
    databaseURL: 'https://controlapp-7f8f5-default-rtdb.firebaseio.com',
    storageBucket: 'controlapp-7f8f5.appspot.com',
    iosBundleId: 'com.example.controlapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYImF-uGW1-zc4gVQLMvOMqf3bkL3J7j0',
    appId: '1:81898159963:web:2bb5a1380ac3bd5b75e47e',
    messagingSenderId: '81898159963',
    projectId: 'controlapp-7f8f5',
    authDomain: 'controlapp-7f8f5.firebaseapp.com',
    databaseURL: 'https://controlapp-7f8f5-default-rtdb.firebaseio.com',
    storageBucket: 'controlapp-7f8f5.appspot.com',
    measurementId: 'G-9NE7M52BV5',
  );
}